### ISSUE TITLE
找不到库

### ISSUE THREAD

**Issue by runryan** [SmallRaw/BlockchainWallet-Crypto#30]
在readme中说引用库的方式是`implementation 'com.github.SmallRaw:BlockchainWallet-Crypto:last-version'`.看了最新的标签是`v0.1.15-beta`,所以的我的工程中配置如下，`implementation 'com.github.SmallRaw:BlockchainWallet-Crypto:v0.1.15-beta'`,编译出错，提示
> Could not resolve com.github.SmallRaw:BlockchainWallet-Crypto:v0.1.15-beta

这里的版本号要配置多少？

**Comment by QuincySx** [comment]
maven { url 'https://jitpack.io' } 仓库地址没有配置吧

**Comment by runryan** [comment]
@QuincySx jitpack也配置了的，版本号那里设置有问题没？

**Comment by QuincySx** [comment]
jitpack 好像是又出故障了

**Comment by QuincySx** [comment]
maven { url "https://raw.githubusercontent.com/QuincySx/mvn-repo/master/repository" }

先配置这个仓库吧，jitpack 大概是炸了

**Comment by runryan** [comment]
@QuincySx 多谢!应该是jitpack的问题，我试了其他的jitpack库，也是不行。`clean project`, `rebuild`了一下，反正这会儿时OK的了
