### ISSUE TITLE
有MnemonicCode这个类吗？

### ISSUE THREAD

**Issue by runryan** [SmallRaw/BlockchainWallet-Crypto#31]
我看Readme中提到了MnemonicCode这个类，并且非常方便调用。但是在添加了库之后，库中并没有这个类。怎么弄？

**Comment by QuincySx** [comment]
有但是调不到，正准备要移除呢，现在大部分 API 都不稳定

**Comment by runryan** [comment]
我看了，这个类是[bitcoinj](https://github.com/bitcoinj/bitcoinj)库里面的
